server {
    listen 80;
    server_name localhost;

    # 1. Servir la página web
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto soluciona el problema de recargar la página (F5) en React (SPA)
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy para las peticiones normales a la API
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Proxy especial para los WebSockets
    location /ws-diagram/ {
        proxy_pass http://backend:8080/ws-diagram/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
