version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_diagramador
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2077
      POSTGRES_DB: diagramador_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: springboot_diagramador
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: